Task №3
Akros2016/ort-dnepr-javacore-medvedev pull request #10
Opened 2016-12-23 11:31 UTC by Akros2016

Первый коммит этой задачи. Запилил пока только сложение и вычитание.
Жду отвтета сэнсэя.

2017-01-08 10:25 UTC, strazhkoe requested changes

2017-01-08 10:25 UTC, strazhkoe commented on src/task_from_teacher_3/FractionsMedvedev.java
> +	/** При параметре _degreeOfFractionalPart = 1
что это за параметр?

2017-01-08 10:25 UTC, strazhkoe commented on src/task_from_teacher_3/Main.java
> +		long commonDenominator = a.getFractionPart() * b.getFractionPart();
все методы арифметических операций должны быть внутри класса дроби и не должны быть static

2017-01-08 14:32 UTC, Akros2016 commented on src/task_from_teacher_3/FractionsMedvedev.java
> +	/** При параметре _degreeOfFractionalPart = 1
Этот параметр должен был быть для десятичных дробей. Например если задать дробную часть   "3", то как понять это 0,3 или 0,0003 ?! Для этого и ввел этот параметр, который указывает степень дробной части.

2017-01-08 14:36 UTC, Akros2016 commented
+	/** При параметре _degreeOfFractionalPart = 1
>
> что это за параметр?
>
Этот параметр должен был быть для десятичных дробей. Например если задать
дробную часть "3", то как понять это 0,3 или 0,0003 ?! Для этого и ввел
этот параметр, который указывает степень дробной части.



>

2017-01-17 21:00 UTC, strazhkoe requested changes

2017-01-17 21:00 UTC, strazhkoe commented on src/task_from_teacher_3/FractionsMedvedev.java
> +		;
Лишняя точка с запятой

2017-01-17 21:00 UTC, strazhkoe commented on src/task_from_teacher_3/FractionsMedvedev.java
> +	public void summ(FractionsMedvedev a, FractionsMedvedev b) {
Метод должен суммировать this с входящим аргументом. То есть аргумент должен быть один. Так для всех операций.

2017-02-03 11:03 UTC, strazhkoe commented on src/task_from_teacher_3/FractionsMedvedev.java
> +	/** При параметре _degreeOfFractionalPart = 1
Если он должен был быть и сейчас не нужен, то его надо удалить

2017-02-03 11:06 UTC, strazhkoe commented
Удали из джавадока параметр, добавь джавадоки к остальным публичным методам

2017-02-15 20:31 UTC, Akros2016 commented
What's wrong ?

2017-03-12 14:35 UTC, Akros2016 commented
Жень, пожалуйста, глянь исправления.

2017-03-18 20:00 UTC, Akros2016 commented
Whyyyyyyyyy?(

2017-03-25 19:51 UTC, strazhkoe approved these changes

2017-03-25 19:51 UTC, merged