Task №13.  (this task pushed not in correct branch)
Akros2016/ort-dnepr-javacore-medvedev pull request #12
Opened 2017-01-12 10:20 UTC by Akros2016

First commit. I have not fulfilled the last condition (Предусмотрите
ситуацию, когда у одного автовладельца может быть несколько автомобилей)

2017-01-29 12:49 UTC, strazhkoe requested changes

2017-01-29 12:49 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +	Map<String,List<String>> _manAndCarNumber = new HashMap<String,List<String>>();
Почему без спецификатора доступа? Будет использоваться внутри пакета?

2017-01-29 12:49 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +		return _manAndCarNumber;
Нужно возвращать неизменяемую мапу

2017-01-29 12:49 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +	public void setManAndCarNumber(Map<String, List<String>> manAndCarNumber) {
Думаю, что этот метод вообще стоит удалить

2017-01-29 12:49 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +	public void putElement(String name, List<String> number){
плохое название метода, ни о чем не говорит. Тем более нет джавадока, описывающего аргументы

2017-01-29 12:49 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +		_manAndCarNumber.remove(name);
Как узнать, успешно удалился или нет или его вообще там небыло?

2017-01-29 12:49 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +		if(this._manAndCarNumber.containsKey(name) == true ){
== true лишнее

2017-01-29 12:49 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +			this._manAndCarNumber.put(newName,newNumber);
метод put перезатирает старое значение. Нет необходимости предварительно удалять. См. https://docs.oracle.com/javase/7/docs/api/java/util/Map.html#put(K,%20V)

2017-01-29 12:49 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +				System.out.println(result + " is owner of tne car number " + number);
Результат нужно вернуть, а не печатать. Вдруг он не для печать нужен?

2017-01-29 12:49 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +	public void print() {
нужно перенести из этого класса

2017-01-29 12:49 UTC, strazhkoe commented on src/task_from_teacher_13/CarNumberComparator.java
> +public class CarNumberComparator implements Comparator<Map.Entry<String, List<String>>> {
Джавадок!!!

2017-02-15 20:33 UTC, Akros2016 commented
What's wrong ?

2017-02-19 10:07 UTC, strazhkoe requested changes

2017-02-19 10:07 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +	public void addNewElement(String name, List<String> number){
Не намного лучше старого названия. Назови его например addCarOwner или что-то около этого

2017-02-19 10:07 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +			System.out.println("Записи с именем " + name + " не найдено. Уточните данные.");
этот метод должен возвращать результат выполнения операции, а выводы в интерфейс должны быть сделаны в классе, отвечающим за общение с пользователем

2017-02-19 10:07 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
>  	public void editElement(String name, String newName, List<String> newNumber){
нет обратной связи, метод ничего не возвращает. А если такого элемента нет, то метод просто промолчит?

2017-03-13 19:42 UTC, strazhkoe requested changes

2017-03-13 19:42 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +		if (_manAndCarNumber.containsKey(name)) {
Ты же только что сюда положил пару с этим ключем? Зачем теперь это проверять? Есть ли такие случаи, когда можно выполнить put, и пара не добавится в мапу?

2017-03-13 19:42 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +		return _manAndCarNumber;
Забыл за этот комментарий?

2017-03-13 19:42 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +		if (_manAndCarNumber.containsKey(name)) {
весь этот if-else можно заменить на return _manAndCarNumber.containsKey(name). Но нужно ли это? См. комментарий выше

2017-03-13 19:42 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +	}
Весь этот метод заменяется одной строчкой:
`
return _manAndCarNumber.remove(name) != null
`
Читай javadoc к интерфейсу Map, особенно те методы, что собираешься использовать

2017-03-13 19:42 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +	}
А удалить запись под ключем name? Ты создал новую, но не удалил старую

2017-03-13 19:42 UTC, strazhkoe commented on src/task_from_teacher_13/CarNumberComparator.java
> +		return o1.getValue().toString().compareTo(o2.getValue().toString());
а если в двух списках одни и те же номера будут идти в разном порядке эти списки будут различны? Это правильно?

2017-03-18 09:40 UTC, Akros2016 commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +		if (_manAndCarNumber.containsKey(name)) {
Ты же сам где то писал, что нужно проверять, успешно ли прошла операция и как-то об этом сигнализировать !

2017-03-18 20:01 UTC, Akros2016 commented on src/task_from_teacher_13/CarNumberComparator.java
> +		return o1.getValue().toString().compareTo(o2.getValue().toString());
То есть сначала отсортировать номера внутри самого листа  ?

2017-03-25 19:57 UTC, strazhkoe requested changes

2017-03-25 19:57 UTC, strazhkoe commented on src/task_from_teacher_13/CarNumberComparator.java
> +		return o1.getValue().toString().compareTo(o2.getValue().toString());
Класс, как я смотрю, вообще не используется. Можно его удалить

2017-11-22 09:39 UTC, closed without merging