Task from teacher 14 calculator
Akros2016/ort-dnepr-javacore-medvedev pull request #13
Opened 2017-02-15 23:00 UTC by Akros2016

2017-02-19 11:08 UTC, strazhkoe requested changes

2017-02-19 11:08 UTC, strazhkoe commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +public class AutoOwnerDirectory {
что тут делает этот класс?

2017-02-19 11:08 UTC, strazhkoe commented on src/task_from_teacher_14/CalculationHistory.java
> +	public String stringBuilding(String date, String query, double result){
этот метод должен быть public?

2017-02-19 11:08 UTC, strazhkoe commented on src/task_from_teacher_14/CalculationHistory.java
> +		File saveFile = new File("Calculation_history.txt");
имя файла нужно вынести куда-то

2017-02-19 11:08 UTC, strazhkoe commented on src/task_from_teacher_14/CalculationHistory.java
> +	public void showHistory() {
общения с пользователем тут быть не должно

2017-02-19 11:08 UTC, strazhkoe commented on src/task_from_teacher_14/CalculatorService.java
> +	double evaluate (ArrayList<String> s) throws Exception;
Почему throws Exception? Более точное исключение можно тут подобрать?

2017-02-19 11:08 UTC, strazhkoe commented on src/task_from_teacher_14/Main.java
> +		}
Возникновение любой из этих ошибок должно привести к завершению программы? Нельзя ни одну обработать так, чтобы пользователь мог продолжить работу?

2017-02-19 11:08 UTC, strazhkoe commented on src/task_from_teacher_14/ConsoleUserInterface.java
> +			//s.close();
Почему закрытие сканера закоментировано?

2017-03-12 16:13 UTC, Akros2016 commented on src/task_from_teacher_14/ConsoleUserInterface.java
> +			//s.close();
Оно конфликтовало со сканером в Main.

2017-03-12 16:27 UTC, Akros2016 commented on src/task_from_teacher_13/AutoOwnerDirectory.java
> +public class AutoOwnerDirectory {
Erroneous addition !

2017-03-12 16:29 UTC, Akros2016 commented on src/task_from_teacher_14/CalculationHistory.java
> +	public void showHistory() {
Его там вроде бы как и нет.

2017-03-25 19:45 UTC, strazhkoe requested changes

2017-03-25 19:45 UTC, strazhkoe commented on src/task_from_teacher_14/Main.java
> +			cui.start();
этот метот в блоках catch позволяет пользователю что-то ввести и на этом программа заканчивается. Нужно зациклить логику чтобы пользователь мог после ошибки ввести выражение снова и ему выдался бы результат. В остальном все неплохо.

2017-11-22 09:39 UTC, closed without merging