Task №11
Akros2016/ort-dnepr-javacore-medvedev pull request #8
Opened 2016-12-17 15:08 UTC by Akros2016

First commit of this task.

2016-12-25 21:04 UTC, strazhkoe requested changes

2016-12-25 21:04 UTC, strazhkoe commented on src/task_from_teacher_11/Main.java
> +		}
чтобы не копипастить эту логику, переопредели toString у рабочего

2017-01-09 12:49 UTC, strazhkoe requested changes

2017-01-09 12:49 UTC, strazhkoe commented on src/task_from_teacher_11/PaymentComparator.java
> +			result = Double.compare(w1.getName().charAt(0), w2.getName().charAt(0)) * (-1);
Тут лучше сделать w1.getName().compareTo(w2.getName()). Тогда будет сравнение по всем буквам имени

2017-01-09 12:49 UTC, strazhkoe commented on src/task_from_teacher_11/Worker.java
> +	protected double _payment;
поле должно быть приватным

2017-01-09 12:49 UTC, strazhkoe commented on src/task_from_teacher_11/Worker.java
> +		_id = id;
Используй гет и сет методы

2017-01-09 12:49 UTC, strazhkoe commented on src/task_from_teacher_11/Worker.java
> +		return sb.toString();
тут можно делать склеивание через плюс. Все равно будет неявно создаваться билдер. Явное использование StringBuilder имеет смысл в более сложных сборах строки, например - через цикл

2017-01-17 21:05 UTC, strazhkoe commented
Добавь, пожалуйста, джавадоки на английском

2017-02-03 14:59 UTC, strazhkoe commented on src/task_from_teacher_11/Main.java
> +	/** method for printing workers and payments*/
все джавадоки подразумевают описание входящих параметров и возвращающих значений. Тут не описан параметр workers. Тут и ниже. Добавь пожалуйста

2017-02-15 20:33 UTC, Akros2016 commented
What's wrong ?

2017-02-24 20:26 UTC, Akros2016 commented
Жень, please, check this corrections.

2017-03-13 19:46 UTC, strazhkoe requested changes

2017-03-13 19:46 UTC, strazhkoe commented on src/task_from_teacher_11/Worker.java
>  	public abstract void avrgMonSalary(double x);
Метод должен что-то возвращать? Почему он публичный? Кто его должен вызывать и зачем если он void?

2017-03-13 19:46 UTC, strazhkoe commented on src/task_from_teacher_11/Main.java
> +	 * @param workers
А описание к параметру?

2017-03-18 09:05 UTC, Akros2016 commented on src/task_from_teacher_11/Worker.java
>  	public abstract void avrgMonSalary(double x);
Публичный для того, чтобы использовать вычисление средней зп например для других категорий работников. Остальное исправил.

2017-03-25 19:50 UTC, strazhkoe commented on src/task_from_teacher_11/Worker.java
>  	public abstract void avrgMonSalary(double x);
Попробовал изменить на protected - компилятор не ругался. Значит метод не используется за пределами иерархии классов.

2017-03-25 19:50 UTC, strazhkoe approved these changes

2017-03-25 19:50 UTC, merged